### PR TITLE
add auth0 OAuth2 backend

### PR DESCRIPTION
**Pull request by daniel-milemarker**
- added social-core auth0 module and python-jose

### CODE REVIEW

**Comment by daniel-milemarker** [comment]
Auth0 Configuration in the admin panel:

Name: Yam Edu
Skip registration form: check
Skip email verification: check
Visibile: check
Enable sso id verification: check
Backend: auth0
ClientId: GgpumGAW3cjbyeGQarRCH82R6tsunojR
Other settings:
```
{
    "DOMAIN": "litvak.auth0.com",
    "SCOPE": [
        "openid",
        "profile",
        "email"
    ]
}
```

**Comment by daniel-milemarker** [comment]
Switched to using a [custom auth0 backend plugin](https://github.com/yameducation/edx-oauth2-auth0-backend) since we need to use a custom plugin since the social-core.auth0 backend does not handle the [auth_exchange](https://github.com/openedx/edx-platform/tree/master/openedx/core/djangoapps/auth_exchange) endpoints correctly.

**Review by lpm0073 — CHANGES_REQUESTED** [review]
Modifications to the requirements.txt are taken care of for you for edx-oauth2-auth0-backend, in the Github Action openedx-actions/tutor-plugin-build-openedx-add-requirement@v1.0.3, so you should remove this line

**Comment by lpm0073** [comment]
Sorry for unnecessarily dragging this process out, but on further inspection you also need to move python-jose from private.txt to a new snippet in https://github.com/yameducation/openedx_devops2/blob/main/.github/workflows/build-openedx.yml#L85

Clarifying: you do not manipulate private.txt yourself for anything, at all. In fact, requirements.txt is very likely deprecated for all practical purposes since its dynamically created by openedx-actions/tutor-plugin-build-openedx-add-requirement

**Pull request merged**
